"""Schema-typed test doubles for the ingestion framework.

A permissive in-memory fake once masked a real type mismatch: the framework wrote
`source_record.version_id = "{sid}#1"` (text) into an INTEGER column — tests were
green, live 400'd (lesson L-007). These fakes reject any write whose Python value
type wouldn't survive the real Postgres column, so that class of bug fails in the
test suite instead.

Type map, so it can't drift silently:
- source_version / ingestion_run / security_event / organization_alias are
  DERIVED FROM db/migrations/*.sql at import (fresh every run).
- source_record predates the migrations (no DDL in db/migrations), so its types
  come from tests/fixtures/pg_column_types.json (a committed live snapshot,
  regenerated by scripts/db/dump_column_types.py).
- test_ingestion_types.py cross-checks the migration-derived types against that
  live snapshot — if a migration and live disagree, that test fails.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from uuid import uuid4

from app.services.ingestion.base import Backend

ROOT = Path(__file__).resolve().parents[1]
MIG = ROOT / "db" / "migrations"
SNAPSHOT = json.loads((ROOT / "tests" / "fixtures" / "pg_column_types.json").read_text())

TARGET_TABLES = ["source_record", "source_version", "ingestion_run",
                 "security_event", "organization_alias"]
_MIGRATION_TABLES = ["source_version", "ingestion_run", "security_event", "organization_alias"]

# pg type token → coarse python category the value must satisfy
_CATEGORY = {
    "text": "str", "varchar": "str", "uuid": "str",
    "timestamptz": "str", "timestamp": "str", "date": "str",
    "integer": "int", "int": "int", "int4": "int", "int8": "int",
    "bigint": "int", "smallint": "int", "serial": "int",
    "boolean": "bool", "bool": "bool",
    "float8": "num", "float": "num", "real": "num", "numeric": "num",
    "double precision": "num", "double": "num",
    "jsonb": "json", "json": "json",
    "vector": "vec",
}


def _norm_type(tok: str) -> str:
    return re.sub(r"\(\d+\)", "", tok.strip().rstrip(",").lower())


def category(pgtype: str) -> str:
    return _CATEGORY.get(_norm_type(pgtype), "any")


# ── derive migration-defined column types from db/migrations/*.sql ───

def _balanced_body(sql: str, table: str) -> str | None:
    m = re.search(r"CREATE TABLE (?:IF NOT EXISTS )?" + re.escape(table) + r"\s*\(", sql, re.I)
    if not m:
        return None
    i = m.end() - 1
    depth = 0
    for j in range(i, len(sql)):
        if sql[j] == "(":
            depth += 1
        elif sql[j] == ")":
            depth -= 1
            if depth == 0:
                return sql[i + 1:j]
    return None


def _split_top_commas(body: str) -> list[str]:
    parts, depth, cur = [], 0, ""
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur); cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur)
    return parts


_NOT_A_COLUMN = {"CONSTRAINT", "PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "EXCLUDE"}


def _cols_from_body(body: str) -> dict[str, str]:
    cols: dict[str, str] = {}
    for part in _split_top_commas(body):
        toks = part.strip().split()
        if len(toks) < 2 or toks[0].upper() in _NOT_A_COLUMN:
            continue
        cols[toks[0].lower()] = _norm_type(toks[1])
    return cols


def types_from_migrations() -> dict[str, dict[str, str]]:
    """{table: {column: pgtype}} parsed from CREATE TABLE + ALTER ADD COLUMN."""
    types: dict[str, dict[str, str]] = {}
    for f in sorted(MIG.glob("*.sql")):
        sql = re.sub(r"--[^\n]*", "", f.read_text(encoding="utf-8"))
        for tm in re.finditer(r"CREATE TABLE (?:IF NOT EXISTS )?(\w+)", sql, re.I):
            tbl = tm.group(1).lower()
            body = _balanced_body(sql, tbl)
            if body:
                for c, t in _cols_from_body(body).items():
                    types.setdefault(tbl, {}).setdefault(c, t)
        for am in re.finditer(
                r"ALTER TABLE (\w+)(.*?);",
                sql, re.S | re.I):
            tbl = am.group(1).lower()
            for cm in re.finditer(
                    r"ADD COLUMN (?:IF NOT EXISTS )?(\w+)\s+([A-Za-z0-9_]+(?:\(\d+\))?)",
                    am.group(2), re.I):
                types.setdefault(tbl, {}).setdefault(cm.group(1).lower(), _norm_type(cm.group(2)))
    return types


MIGRATION_TYPES = types_from_migrations()

# The authoritative map the fakes validate against.
COLUMN_TYPES: dict[str, dict[str, str]] = {"source_record": dict(SNAPSHOT["source_record"])}
for _t in _MIGRATION_TABLES:
    COLUMN_TYPES[_t] = MIGRATION_TYPES[_t]


# ── the type guard ──────────────────────────────────────────────────

def check_row(table: str, row: dict) -> None:
    """Raise TypeError if any value's Python type wouldn't survive its Postgres
    column (or the column is unknown). None is allowed (SQL NULL)."""
    schema = COLUMN_TYPES.get(table)
    if schema is None:
        return
    for col, val in row.items():
        if col not in schema:
            raise TypeError(f"{table}: unknown column {col!r} (PostgREST would 400)")
        if val is None:
            continue
        cat = category(schema[col])
        ok = (
            (cat == "str" and isinstance(val, str))
            or (cat == "int" and isinstance(val, int) and not isinstance(val, bool))
            or (cat == "bool" and isinstance(val, bool))
            or (cat == "num" and isinstance(val, (int, float)) and not isinstance(val, bool))
            or (cat == "json" and isinstance(val, (dict, list, str, int, float, bool)))
            or (cat == "vec" and isinstance(val, (str, list)))
            or cat == "any"
        )
        if not ok:
            raise TypeError(
                f"{table}.{col}: {type(val).__name__} {val!r} is not valid for "
                f"Postgres type {schema[col]!r} (would fail on insert)")


# ── typed fakes ─────────────────────────────────────────────────────

class TypedFakeBackend(Backend):
    """In-memory Backend that enforces live column types on every write."""

    def __init__(self):
        self.source_records: dict[str, dict] = {}
        self.source_versions: dict[str, list[dict]] = {}
        self.raw_objects: dict[str, bytes] = {}
        self.parser_versions: dict[tuple, str] = {}
        self.runs: dict[str, dict] = {}

    def find_source_record(self, sid):
        return self.source_records.get(sid)

    def latest_version_hash(self, sid):
        v = self.source_versions.get(sid) or []
        return v[-1]["hash"] if v else None

    def version_count(self, sid):
        return len(self.source_versions.get(sid) or [])

    def store_raw(self, path, data, ct):
        if path in self.raw_objects:
            return "reused"
        self.raw_objects[path] = data
        return "created"

    def create_source_record(self, row):
        check_row("source_record", row)
        self.source_records[row["source_id"]] = row

    def create_source_version(self, row):
        check_row("source_version", row)
        self.source_versions.setdefault(row["source_id"], []).append(row)

    def register_parser_version(self, family, version, desc):
        self.parser_versions.setdefault((family, version), f"pv-{family}-{version}")
        return self.parser_versions[(family, version)]

    def create_ingestion_run(self, row):
        check_row("ingestion_run", row)
        rid = str(uuid4())
        self.runs[rid] = dict(row)
        return rid

    def finish_ingestion_run(self, rid, updates):
        check_row("ingestion_run", updates)
        self.runs[rid].update(updates)


class FakeOrgStore:
    """In-memory OrgStore double for the sec_edgar connector. Enforces the live
    UNIQUE(alias_type, value) and UNIQUE(slug) constraints, does additive-only
    null enrichment, and type-checks every organization_alias write against the
    live column snapshot (same guard the backend fakes use)."""

    def __init__(self):
        self.orgs: dict[str, dict] = {}
        self.aliases: dict[tuple, dict] = {}          # (alias_type, value) -> row  (UNIQUE)
        self._slugs: set[str] = set()
        self._seq = 0

    # -- deterministic id (no Math.random/uuid needed for test determinism) --
    def _new_id(self) -> str:
        self._seq += 1
        return f"00000000-0000-4000-8000-{self._seq:012d}"

    # -- seeding helper for tests (pre-existing orgs) --
    def seed_org(self, **fields) -> str:
        oid = fields.pop("organization_id", None) or self._new_id()
        slug = fields.get("slug") or oid
        self._slugs.add(slug)
        self.orgs[oid] = {"organization_id": oid, "slug": slug, **fields}
        return oid

    def find_org_id_by_alias(self, alias_type: str, value: str):
        row = self.aliases.get((alias_type, value))
        return row["organization_id"] if row else None

    def find_org_id_by_domain(self, normalized_domain: str):
        from app.services.ingestion.connectors.edgar import normalize_domain
        for oid, o in self.orgs.items():
            if normalize_domain(o.get("domain")) == normalized_domain:
                return oid
        return None

    def find_org_id_by_slug(self, slug: str):
        for oid, o in self.orgs.items():
            if o.get("slug") == slug:
                return oid
        return None

    def get_org(self, org_id: str):
        return self.orgs.get(org_id)

    def create_org(self, fields: dict):
        from app.services.ingestion.connectors.edgar import ORG_COLUMNS, slugify
        payload = {k: v for k, v in fields.items() if k in ORG_COLUMNS}
        base = payload.get("slug") or slugify(payload.get("name", "org"))
        slug, n = base, 1
        while slug in self._slugs:                     # honor UNIQUE(slug)
            slug = f"{base}-{fields.get('_cik', n)}-{n}"; n += 1
        payload["slug"] = slug
        self._slugs.add(slug)
        oid = self._new_id()
        self.orgs[oid] = {"organization_id": oid, **payload}
        return oid

    def patch_org_nulls(self, org_id: str, fields: dict):
        from app.services.ingestion.connectors.edgar import ENRICHABLE_COLUMNS
        org = self.orgs[org_id]
        filled = []
        for k, v in fields.items():
            if k in ENRICHABLE_COLUMNS and v is not None and org.get(k) is None:
                org[k] = v; filled.append(k)
        return sorted(filled)

    def upsert_alias(self, row: dict) -> bool:
        from app.services.ingestion.connectors.edgar import ALIAS_COLUMNS
        key = (row["alias_type"], row["value"])
        if key in self.aliases:                        # ON CONFLICT(alias_type,value) DO NOTHING
            return False
        stored = {k: v for k, v in row.items() if k in ALIAS_COLUMNS}
        stored["alias_id"] = self._new_id()
        check_row("organization_alias", stored)        # live-type guard (as PostgREST would)
        self.aliases[key] = stored
        return True


class TypedFakeEventWriter:
    """security_event upsert double (ON CONFLICT (event_id) DO NOTHING) that also
    type-checks each row and rejects the framework's non-column lineage field."""

    def __init__(self):
        self.rows: dict[str, dict] = {}

    def __call__(self, rows):
        n = 0
        for r in rows:
            assert "parser_version_id" not in r          # not a security_event column
            check_row("security_event", r)
            if r["event_id"] not in self.rows:
                self.rows[r["event_id"]] = r
                n += 1
        return n
