"""Generated PDF palette and stable risk-boundary contracts."""

import re

from app.services.report.renderer import _ramp_key
from scripts.build_report_css import build_outputs, oklch_to_rgb


def test_light_theme_standing_tokens_convert_to_expected_srgb():
    assert oklch_to_rgb("oklch(0.520 0.108 163.3)") == ((15, 124, 87), 1.0, False)
    assert oklch_to_rgb("oklch(0.545 0.125 77.5)") == ((152, 100, 0), 1.0, True)
    assert oklch_to_rgb("oklch(0.500 0.182 29.5)") == ((180, 35, 24), 1.0, False)


def test_report_assets_are_deterministic_and_all_hex_values_are_traced():
    first = build_outputs()
    second = build_outputs()
    assert first == second
    css, python_module, clamped = first
    assert css.startswith("/* GENERATED by scripts/build_report_css.py")
    assert "standing-mid" in clamped
    assert '"standing_good": "#0F7C57"' in python_module

    # Runtime literals only occur in generated token declarations, each with
    # an adjacent source comment. Layout rules consume named variables.
    for line in css.splitlines():
        if re.search(r"#[0-9A-Fa-f]{3,8}\b", line):
            assert "source: theme.css" in line


def test_existing_risk_cutpoints_remain_unchanged():
    assert _ramp_key(24.999) == "low"
    assert _ramp_key(25) == "moderate"
    assert _ramp_key(49.999) == "moderate"
    assert _ramp_key(50) == "high"
    assert _ramp_key(74.999) == "high"
    assert _ramp_key(75) == "elevated"
