"""GENERATED by scripts/build_report_css.py; do not edit."""

REPORT_COLORS = {
    "primary": "#161B1D",  # theme.css --primary
    "primary_foreground": "#F9FBFB",  # theme.css --primary-foreground
    "muted_foreground": "#5E6F73",  # theme.css --muted-foreground
    "border": "#DBE1E2",  # theme.css --border
    "ring": "#9CA8AB",  # theme.css --ring
    "brand": "#2A76C3",  # theme.css --brand
    "standing_good": "#0F7C57",  # theme.css --standing-good
    "standing_mid": "#986400",  # theme.css --standing-mid
    "standing_bad": "#B42318",  # theme.css --standing-bad
}
