import { ArrowDown, ArrowUpRight, Activity, FileText, Layers, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { ClosingNote, Eyebrow, PerspectiveArt, Pipeline, Reveal, SiteLink } from "./shared";
import { AudienceExplorer, CapabilityRoadmap, PlanComparison, ProductGrid, ProductTour, WorkspaceTour } from "./ProductShowcase";
export function Home() {
  return <>
    <section className="site-hero site-wrap commercial-hero"><div className="site-hero-copy"><Eyebrow>The privacy intelligence platform</Eyebrow><h1>Understand privacy.<br /><em>Act with perspective.</em></h1><p className="site-hero-description">Assess disclosures. Monitor change.<br />Put intelligence to work.</p><p className="site-hero-detail">One platform for notice assessments, ongoing monitoring and white-label reports. Built for the teams and advisors making privacy decisions.</p><div className="site-actions"><SiteLink to="/solutions">Explore our products</SiteLink><SiteLink to="/pricing" subtle>View plans</SiteLink></div><a className="site-scroll-cue" href="#product-tour"><ArrowDown size={14}/>Take a product walkthrough</a></div><div className="commercial-hero-stage"><PerspectiveArt/><div className="hero-software-window"><WorkspaceTour compact/></div><span className="hero-stage-caption">STRUCTURED EVIDENCE. CONNECTED INTELLIGENCE.</span></div></section>
    <section className="product-category-strip"><div className="site-wrap">{[[FileText,"Notice assessments"],[Activity,"Continuous monitoring"],[Users,"White-label intelligence"],[Layers,"Quarterly publications"]].map(([Icon,text])=>{const Glyph=Icon as typeof FileText;return <span key={String(text)}><Glyph size={17}/>{String(text)}</span>;})}</div></section>
    <section className="site-section site-wrap" id="products"><Reveal><div className="site-section-heading"><div><Eyebrow>Our products</Eyebrow><h2>One intelligence engine.<br /><em>Four ways to use it.</em></h2></div><p className="section-side-copy">Start with an assessment. Build an ongoing view. Deliver it under your brand. Explore the wider landscape.</p></div></Reveal><ProductGrid/></section>
    <ProductTour/>
    <section className="site-manifesto technology-band"><div className="site-wrap"><Reveal><div className="site-section-heading"><div><Eyebrow>Technology with a clear purpose</Eyebrow><h2>From unstructured notices<br /><em>to connected intelligence.</em></h2></div><SiteLink to="/platform">Explore the platform</SiteLink></div><p className="technology-intro">AI-assisted classification structures the disclosures. Deterministic formulas calculate the intelligence. Source references and confidence give you the context to interpret it.</p><Pipeline/></Reveal></div></section>
    <AudienceExplorer/>
    <PlanComparison/>
    <CapabilityRoadmap/>
    <section className="site-section site-wrap"><Reveal><div className="site-section-heading"><div><Eyebrow>Research & resources</Eyebrow><h2>Go deeper into<br /><em>the privacy landscape.</em></h2></div><SiteLink to="/resources" subtle>All resources</SiteLink></div><div className="site-editorial-grid"><Link to="/solutions/quarterly-report" className="site-editorial-feature"><div className="site-publication-art" aria-hidden="true"><span>visentix.</span><div>Privacy<br/>intelligence.<br/><em>The wider view.</em></div><i/></div><div><span className="site-kicker">Quarterly intelligence report</span><h3>Individual disclosures.<br/>A collective perspective.</h3><span className="site-inline-arrow">Explore the publication<ArrowUpRight size={18}/></span></div></Link><Link to="/methodology" className="site-editorial-note"><span className="site-kicker">The methodology</span><h3>Look beneath<br/><em>the headline.</em></h3><p>Understand the formulas, sources and review process behind an assessment.</p><span className="site-inline-arrow">Explore the method<ArrowUpRight size={18}/></span></Link></div></Reveal></section>
    <ClosingNote/>
  </>;
}
