import { Check, ArrowUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import { productCatalog, type ProductId } from "./products";
import { ProductVisual, WorkspaceTour } from "./ProductShowcase";
import { ClosingNote, Eyebrow, Reveal, SiteLink } from "./shared";
const details = {
  assessment: { headline: <>Your privacy notice.<br/><em>In full context.</em></>, intro: "Turn a public notice into a structured assessment of disclosure maturity, exposure and peer position. Read the findings, examine the evidence and share the report.", action:"Start an assessment", href:"/intake", overview:"A report that connects the headline to the detail.", blocks:[ ["Understand the disclosure", "Explore the assessed privacy domains, from data sharing and retention to consumer rights and AI disclosure."], ["Place it among peers", "Read benchmark position with the eligible population, as-of date and confidence that give it meaning."], ["Trace the findings", "Follow findings to recorded clauses, source references and the formula version used."], ["Share the intelligence", "Use the executive view, explore analyst detail or export a PDF. Draft and expert-review status remain explicit."] ], note:"An assessment examines public disclosures. It does not assess internal practices, contracts or systems, and does not provide a legal determination." },
  monitoring: { headline: <>Privacy changes.<br/><em>Keep the context.</em></>, intro:"Build an ongoing view of assessed privacy notices. Bring assessment history, trends and disclosure changes into one workspace, with alerts for configured monitoring.", action:"Explore subscriptions", href:"/pricing", overview:"A continuous view, connected to the source.", blocks:[ ["Assessment history", "Revisit the reports and recorded evidence behind each assessed notice."], ["Trend perspective", "Follow stored assessment values over time, with the context needed to interpret change."], ["A shared change feed", "Review recorded notice changes in one place instead of relying on isolated documents."], ["Configured notifications", "Discuss email and webhook delivery as part of your monitoring setup, subject to approved thresholds."] ], note:"Monitoring needs configured sources and assessed notices. Delivery depends on enabled jobs and approved thresholds; subscription scope is confirmed during setup." },
  partner: { headline: <>Your relationships.<br/><em>Your intelligence offering.</em></>, intro:"Bring Visentix into your advisory or consulting service. Organize client workspaces and deliver branded assessment reports through the same underlying intelligence engine.", action:"Discuss partner licensing", href:"/contact?plan=Enterprise", overview:"Our engine. Your client experience.", blocks:[ ["Client workspaces", "Keep individual client assessment work organized within an enabled partner workspace."], ["Branded reporting", "Deliver assessment reports with the partner branding supported by your deployment."], ["Connected delivery", "Scope partner API access and report delivery around your workflow."], ["A tailored agreement", "Agree the client volume, access, delivery scope and licensing model with your Visentix contact."] ], note:"Partner features require an enabled deployment. Branding, API scope and delivery terms are confirmed for the partnership; not every integration is included by default." },
  quarterly: { headline: <>A wider view of<br/><em>privacy intelligence.</em></>, intro:"Explore approved quarterly publications covering disclosure maturity, AI disclosure and recorded enforcement themes. A broader perspective, grounded in its underlying evidence.", action:"Check publication availability", href:"/quarterly", overview:"Individual disclosures. Collective perspective.", blocks:[ ["Disclosure maturity", "A view of the public disclosures represented in the publication’s underlying corpus."], ["AI disclosure", "Explore the AI-related disclosure themes supported by the edition’s evidence."], ["Enforcement themes", "Read recorded activity with its source context and publication scope."], ["Published methodology", "Interpret each edition with its stated evidence, limitations and time period."] ], note:"The reader shows approved editions when available. Trend comparisons depend on approved historical editions; publication dates and corpus size are not assumed." },
};
export function ProductDetail({kind}:{kind:ProductId}) {
  const p=productCatalog.find(p=>p.id===kind)!;const d=details[kind];
  return <><section className="site-wrap product-detail-hero"><div><Link to="/solutions" className="product-breadcrumb">All products / {p.short}</Link><Eyebrow>{p.category}</Eyebrow><h1>{d.headline}</h1><p>{d.intro}</p><div className="site-actions"><SiteLink to={d.href}>{d.action}</SiteLink><SiteLink to="#walkthrough" subtle>Explore the product</SiteLink></div></div><div className={`detail-art tone-${p.tone}`}><ProductVisual kind={kind}/><div><span className="site-kicker">{p.title}</span><ul>{p.features.map(f=><li key={f}><Check size={14}/>{f}</li>)}</ul></div></div></section>
    <section className="product-detail-overview site-soft-band"><div className="site-wrap"><Eyebrow>What it delivers</Eyebrow><h2>{d.overview}</h2><div className="detail-features">{d.blocks.map(([title,text],i)=><Reveal key={title}><span className="site-index">0{i+1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section id="walkthrough" className="site-section site-wrap"><div className="site-section-heading"><div><Eyebrow>Product walkthrough</Eyebrow><h2>Look inside<br/><em>{p.short.toLowerCase()}.</em></h2></div><span className="section-side-copy">Explore the structure and capabilities of the product.</span></div><WorkspaceTour kind={kind}/><p className="site-fine-print">{d.note}</p></section>
    <section className="related-products site-wrap"><Eyebrow>Connected by design</Eyebrow><div>{productCatalog.filter(x=>x.id!==kind).map(x=><Link to={x.path} key={x.id}><span>{x.category}</span><h3>{x.short}</h3><ArrowUpRight size={21}/></Link>)}</div></section><ClosingNote/></>;
}
