#!/usr/bin/env python3
"""Generate the runtime banned-term file from its reviewed source."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "data" / "banned_terms.txt"
TARGET = ROOT / "config" / "banned_terms.txt"
HEADER = "# GENERATED by scripts/build_banned_terms.py — do not edit by hand.\n"


def generated_text() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    if not source.endswith("\n"):
        source += "\n"
    return HEADER + source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if config/banned_terms.txt is not freshly generated",
    )
    args = parser.parse_args()
    expected = generated_text()

    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            print(
                "build_banned_terms: config/banned_terms.txt is stale; "
                "run python3 scripts/build_banned_terms.py",
                file=sys.stderr,
            )
            return 1
        print("build_banned_terms: runtime list is fresh")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"build_banned_terms: wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
