/**
 * ReportView — renders all 12 sections from the payload.
 * This SAME component drives both the portal view and the Playwright PDF.
 * It displays data only — no client-side score recomputation.
 *
 * DDR-001: draft_banner replaced by ProvenanceRibbon + diagonal watermark.
 */
import type { ReportPayload } from "./types";
import { ProvenanceRibbon } from "../components/ProvenanceRibbon";
import { Cover }              from "./sections/Cover";
import { ExecutiveSummary }   from "./sections/ExecutiveSummary";
import { RiskDashboard }      from "./sections/RiskDashboard";
import { BenchmarkIntelligence } from "./sections/BenchmarkIntelligence";
import { RegulatorExposure }  from "./sections/RegulatorExposure";
import { FindingsTable }      from "./sections/FindingsTable";
import { CompoundRisk }       from "./sections/CompoundRisk";
import { BenchmarkLanguage }  from "./sections/BenchmarkLanguage";
import { Recommendations }    from "./sections/Recommendations";
import { RiskReduction }      from "./sections/RiskReduction";
import { Traceability }       from "./sections/Traceability";
import { TrendPanel }         from "./sections/TrendPanel";
import "./report.css";

const SECTION_MAP: Record<number, React.FC<{ content: Record<string, unknown> }>> = {
  1: Cover,
  2: ExecutiveSummary,
  3: RiskDashboard,
  4: BenchmarkIntelligence,
  5: RegulatorExposure,
  6: FindingsTable,
  7: CompoundRisk,
  8: BenchmarkLanguage,
  9: Recommendations,
  10: RiskReduction,
  11: Traceability,
  12: TrendPanel,
};

interface ReportViewProps { report: ReportPayload; }

export function ReportView({ report }: ReportViewProps) {
  const isDraft = !!report.draft_banner;

  // Extract snapshot ID from sections if available (Cover section carries it)
  const coverContent = report.sections.find(s => s.number === 1)?.content ?? {};
  const snapshotId   = (coverContent.snapshot_id as string | undefined) ?? "S-0000";
  const frozenDate   = report.generated_date ?? "—";

  return (
    <div
      className={`report-container ${isDraft ? "draft-watermark-wrap" : ""}`}
      data-testid="report-view"
    >
      {/* DDR-004 + DDR-001: Global provenance ribbon replaces yellow draft_banner */}
      <div style={{ marginBottom: 24 }}>
        <ProvenanceRibbon
          snapshotId={snapshotId}
          frozenDate={frozenDate}
          status={isDraft ? "draft" : "approved"}
        />
      </div>

      {report.sections.map((section) => {
        const Component = SECTION_MAP[section.number];
        if (!Component) return null;
        // Thread snapshot context into every section's content
        const enrichedContent = {
          ...section.content,
          snapshot_id:   coverContent.snapshot_id   ?? snapshotId,
          is_draft:      isDraft,
          cohort_size:   report.cohort_size,
          cohort_date:   report.cohort_date,
          date:          report.generated_date,
          assessment_id: report.assessment_id,
        };
        return (
          <div key={section.number} className="report-page-break">
            <Component content={enrichedContent} />
          </div>
        );
      })}

      <div className="report-footer">
        Generated by Visentix Privacy Intelligence Platform
        &nbsp;·&nbsp;{report.generated_date}
        &nbsp;·&nbsp;Assessment: {report.assessment_id?.slice(0, 12)}
        &nbsp;·&nbsp;Cohort: n={report.cohort_size} as of {report.cohort_date}
      </div>
    </div>
  );
}
