/**
 * ReportView — renders all 12 sections from the payload.
 * This SAME component drives both the portal view and the Playwright PDF.
 * It displays data only — no client-side score recomputation.
 */
import type { ReportPayload } from "./types";
import { Cover } from "./sections/Cover";
import { ExecutiveSummary } from "./sections/ExecutiveSummary";
import { RiskDashboard } from "./sections/RiskDashboard";
import { BenchmarkIntelligence } from "./sections/BenchmarkIntelligence";
import { RegulatorExposure } from "./sections/RegulatorExposure";
import { FindingsTable } from "./sections/FindingsTable";
import { CompoundRisk } from "./sections/CompoundRisk";
import { BenchmarkLanguage } from "./sections/BenchmarkLanguage";
import { Recommendations } from "./sections/Recommendations";
import { RiskReduction } from "./sections/RiskReduction";
import { Traceability } from "./sections/Traceability";
import { TrendPanel } from "./sections/TrendPanel";
import "./report.css";

const SECTION_MAP: Record<number, React.FC<{ content: Record<string, unknown> }>> = {
  1: Cover,
  2: ExecutiveSummary,
  3: RiskDashboard,
  4: BenchmarkIntelligence,
  5: RegulatorExposure,
  6: FindingsTable,
  7: CompoundRisk,
  8: BenchmarkLanguage,
  9: Recommendations,
  10: RiskReduction,
  11: Traceability,
  12: TrendPanel,
};

interface ReportViewProps {
  report: ReportPayload;
}

export function ReportView({ report }: ReportViewProps) {
  return (
    <div className="report-container" data-testid="report-view">
      {report.draft_banner && (
        <div className="draft-banner" data-testid="draft-banner" style={{
          background: "#fef3c7", border: "2px solid #f59e0b", padding: "12px 16px",
          borderRadius: 4, marginBottom: 24, fontWeight: 600, textAlign: "center",
        }}>
          {report.draft_banner}
        </div>
      )}

      {report.sections.map((section) => {
        const Component = SECTION_MAP[section.number];
        if (!Component) return null;
        return (
          <div key={section.number} className="report-page-break">
            <Component content={section.content} />
          </div>
        );
      })}

      <div className="report-footer" style={{
        marginTop: 40, borderTop: "1px solid #e0e0e0", paddingTop: 8,
        fontSize: "0.8em", color: "#9ca3af",
      }}>
        Generated by Visentix Privacy Intelligence Platform · {report.generated_date} ·
        Assessment: {report.assessment_id?.slice(0, 12)}
      </div>
    </div>
  );
}
