/**
 * ReportView — renders all 12 sections from the payload.
 * This SAME component drives both the portal view and the Playwright PDF.
 * It displays data only — no client-side score recomputation.
 *
 * DDR-001: draft_banner replaced by ProvenanceRibbon + diagonal watermark.
 */
import { useEffect, useState } from "react";
import type { ReportPayload } from "./types";
import { api } from "../lib/api";
import { ProvenanceRibbon } from "../components/ProvenanceRibbon";
import { useExplain } from "./explain/ExplainContext";
import "./explain/explain.css";
import { Cover }              from "./sections/Cover";
import { ExecutiveSummary }   from "./sections/ExecutiveSummary";
import { RiskDashboard }      from "./sections/RiskDashboard";
import { BenchmarkIntelligence } from "./sections/BenchmarkIntelligence";
import { RegulatorExposure }  from "./sections/RegulatorExposure";
import { FindingsTable }      from "./sections/FindingsTable";
import { CompoundRisk }       from "./sections/CompoundRisk";
import { BenchmarkLanguage }  from "./sections/BenchmarkLanguage";
import { Recommendations }    from "./sections/Recommendations";
import { RiskReduction }      from "./sections/RiskReduction";
import { Traceability }       from "./sections/Traceability";
import { TrendPanel }         from "./sections/TrendPanel";
import "./report.css";

const SECTION_MAP: Record<number, React.FC<{ content: Record<string, unknown> }>> = {
  1: Cover,
  2: ExecutiveSummary,
  3: RiskDashboard,
  4: BenchmarkIntelligence,
  5: RegulatorExposure,
  6: FindingsTable,
  7: CompoundRisk,
  8: BenchmarkLanguage,
  9: Recommendations,
  10: RiskReduction,
  11: Traceability,
  12: TrendPanel,
};

interface ReportViewProps { report: ReportPayload; }

export function ReportView({ report }: ReportViewProps) {
  const isDraft = !!report.draft_banner;
  const { prefetch } = useExplain();

  // M-10: real plain-English formula descriptions from formula_version.description
  // (14/14 populated). Threaded into every section so lineage drawers stop using
  // hardcoded copy. Empty until loaded → sections fall back to honest absence.
  const [formulaDescs, setFormulaDescs] = useState<Record<string, string>>({});
  useEffect(() => {
    api.get("/api/formulas").then((res: { formulas?: Record<string, { description?: string }> }) => {
      const map: Record<string, string> = {};
      for (const [fid, v] of Object.entries(res.formulas ?? {})) {
        if (v?.description) map[fid] = v.description;
      }
      setFormulaDescs(map);
    }).catch(() => { /* backend down → sections render honest absence */ });
  }, []);

  // Prefetch all explain envelopes when the report loads
  useEffect(() => {
    if (report.assessment_id) {
      prefetch(report.assessment_id);
    }
  }, [report.assessment_id, prefetch]);

  // M-09: prefer the authoritative stored snapshot id + frozen-at threaded
  // from the report_snapshot row; fall back to the Cover section, then honest
  // absence — never a plausible-looking fake ID (Hard Rule 7).
  const coverContent = report.sections.find(s => s.number === 1)?.content ?? {};
  const snapshotId   = report._snapshot_id
    ?? (coverContent.snapshot_id as string | undefined)
    ?? "—";
  const formulaVer   = coverContent.formula_version as string | undefined;
  const frozenDate   = (report._generated_at ?? report.generated_date ?? "—").slice(0, 10) || "—";

  return (
    <div
      className={`report-container ${isDraft ? "draft-watermark-wrap" : ""}`}
      data-testid="report-view"
    >
      {/* DDR-004 + DDR-001: THE provenance ribbon — rendered once, here only
          (audit 2026-07-16: Cover previously rendered a duplicate). */}
      <div style={{ marginBottom: 24 }}>
        <ProvenanceRibbon
          snapshotId={snapshotId}
          formulaVersion={formulaVer}
          frozenDate={frozenDate}
          status={isDraft ? "draft" : "approved"}
        />
      </div>

      {report.sections.map((section) => {
        const Component = SECTION_MAP[section.number];
        if (!Component) return null;
        // Thread snapshot context into every section's content
        const enrichedContent = {
          ...section.content,
          snapshot_id:   snapshotId,
          is_draft:      isDraft,
          formula_descs: formulaDescs,
          cohort_size:   report.cohort_size,
          cohort_date:   report.cohort_date,
          date:          report.generated_date,
          assessment_id: report.assessment_id,
        };
        return (
          <div key={section.number} className="report-page-break">
            <Component content={enrichedContent} />
          </div>
        );
      })}

      <div className="report-footer">
        Generated by Visentix Privacy Intelligence Platform
        &nbsp;·&nbsp;{report.generated_date}
        &nbsp;·&nbsp;Assessment: {report.assessment_id?.slice(0, 12)}
        &nbsp;·&nbsp;Cohort: n={report.cohort_size} as of {report.cohort_date}
      </div>
    </div>
  );
}
